FROM python:3.7.3
#FROM registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-notebooks-manager/mosaic-docker-build:3.7python2.5.5
#LABEL maintainer "Meinhard Ploner <dummy@host.com>"
WORKDIR /code
COPY requirements.txt /
RUN pip install -r /requirements.txt --default-timeout=100 future
COPY ./ ./
EXPOSE 8050
CMD ["python", "./app.py"]